name: atmospeed
description: Calculate standard and non-standard atmosphere properties and speed conversions. Uses 1976 US Standard Atmosphere definitions.
version: 1.0.1
repository: https://github.com/aeroperf/atmospeed
issue_tracker: https://github.com/aeroperf/atmospeed/issues

environment:
  sdk: ">=2.16.1 <3.0.0"

dev_dependencies:
  flutter_lints: ^1.0.0
  test: ^1.21.0

